
import app_config from "@config/app_config";
import setup_type from "./setup_type";

const prefix: string = "ComprehensiveDataTypeTest";

const setup: setup_type = {
    prefix,
    permission: ["admin", "super_admin"],

    api_host: app_config.api_host,
    api_version: app_config.api_version,
    api_end_point: "comprehensive-data-type-tests",

    module_name: "comprehensive-data-type-test",
    store_prefix: "comprehensive_data_type_test",
    route_prefix: "ComprehensiveDataTypeTest",
    route_path: "comprehensive-data-type-test",

    select_fields: [
        "id",
        "basic_string",
            "long_string",
            "short_string",
            "description",
            "long_content",
            "basic_number",
            "quantity",
            "count",
            "typo_integer",
            "user_id",
            "category_id",
            "priority",
            "unsigned_count",
            "unsigned_id",
            "birth_year",
            "is_active",
            "price",
            "weight",
            "amount",
            "birth_date",
            "created_at_fju",
            "event_time",
            "start_time",
            "last_seen",
            "metadata",
            "status_fhdj",
            "difficulty",
            "avatar",
            "document",
            "binary_data",
            "identifier",
            "user_password",
        "status",
        "slug",
        "created_at",
        'deleted_at'
    ],

    sort_by_cols: [
        "id",
        "basic_string",
            "long_string",
            "short_string",
            "description",
            "long_content",
            "basic_number",
            "quantity",
            "count",
            "typo_integer",
            "user_id",
            "category_id",
            "priority",
            "unsigned_count",
            "unsigned_id",
            "birth_year",
            "is_active",
            "price",
            "weight",
            "amount",
            "birth_date",
            "created_at_fju",
            "event_time",
            "start_time",
            "last_seen",
            "metadata",
            "status_fhdj",
            "difficulty",
            "avatar",
            "document",
            "binary_data",
            "identifier",
            "user_password",
        "status",
        "created_at",
    ],
    table_header_data: [
        "id",
        "basic_string",
            "long_string",
            "short_string",
            "description",
            "long_content",
            "basic_number",
            "quantity",
            "count",
            "typo_integer",
            "user_id",
            "category_id",
            "priority",
            "unsigned_count",
            "unsigned_id",
            "birth_year",
            "is_active",
            "price",
            "weight",
            "amount",
            "birth_date",
            "created_at_fju",
            "event_time",
            "start_time",
            "last_seen",
            "metadata",
            "status_fhdj",
            "difficulty",
            "avatar",
            "document",
            "binary_data",
            "identifier",
            "user_password",
        "status",
        "created_at",
    ],
    table_row_data: [
        "id",
        "basic_string",
            "long_string",
            "short_string",
            "description",
            "long_content",
            "basic_number",
            "quantity",
            "count",
            "typo_integer",
            "user_id",
            "category_id",
            "priority",
            "unsigned_count",
            "unsigned_id",
            "birth_year",
            "is_active",
            "price",
            "weight",
            "amount",
            "birth_date",
            "created_at_fju",
            "event_time",
            "start_time",
            "last_seen",
            "metadata",
            "status_fhdj",
            "difficulty",
            "avatar",
            "document",
            "binary_data",
            "identifier",
            "user_password",
        "status",
        "created_at",
    ],
    quick_view_data: [
        "id",
        "basic_string",
            "long_string",
            "short_string",
            "description",
            "long_content",
            "basic_number",
            "quantity",
            "count",
            "typo_integer",
            "user_id",
            "category_id",
            "priority",
            "unsigned_count",
            "unsigned_id",
            "birth_year",
            "is_active",
            "price",
            "weight",
            "amount",
            "birth_date",
            "created_at_fju",
            "event_time",
            "start_time",
            "last_seen",
            "metadata",
            "status_fhdj",
            "difficulty",
            "avatar",
            "document",
            "binary_data",
            "identifier",
            "user_password",
        "status",
        "created_at",
    ],

    layout_title: prefix + " Management",
    page_title: `${prefix} Management`,

    all_page_title: "All " + prefix,
    details_page_title: "Details " + prefix,
    create_page_title: "Create " + prefix,
    edit_page_title: "Edit " + prefix,
};

export default setup;
